name: workflow-practice

on:
  push:
    branches: [main]


jobs:

  great:
    runs-on: ubuntu-latest
    steps:
      - name: great to users
        run: echo "hello ${{ github.actor }}"
      - name: great to all
        run: echo "hello eveyone"
