
name: new-workflow
on:
  push:
    branches:
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
        - name: pull docker image
          run: docker pull nginx:latest
        - name: docker status
          run: |
            docker --version
            docker ps
        - name: run container
          run: docker run -d --name web-server -p 8080:80 nginx:latest
        - name: check container running
          run: |
            docker ps 
            curl -f http://localhost:8080
  version-job:
    runs-on: ubuntu-latest
    steps:
      - name: show the versions
        # Pro-Tip: Use python3 for modern Ubuntu images
        run: docker --version && python3 --version
          
           

